server:
  port: 8081

spring:
  application:
    name: sales-service
  
  datasource:
    url: ${DATASOURCE_URL}
  
  jpa:
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
    #     connection:
    #       provider_disables_autocommit: true
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000 