version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: servicodevendas-postgres
    environment:
      POSTGRES_DB: servicodevendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - servicodevendas-network

volumes:
  postgres_data:

networks:
  servicodevendas-network:
    driver: bridge 