server:
  port: 8083

spring:
  application:
    name: sales-registry-service
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:salesdb}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
      authentication-database: admin
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true 