server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/products/**, /api/orders/**
          filters:
            - StripPrefix=0
        
        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/api/tax/**
          filters:
            - StripPrefix=0
        
        - id: sales-registry-service
          uri: lb://sales-registry-service
          predicates:
            - Path=/api/sales-registry/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true 