version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: servicodevendas-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - servicodevendas-network

  eureka-server:
    image: openjdk:21-jdk-slim
    container_name: servicodevendas-eureka
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    ports:
      - "8761:8761"
    command: java -jar target/eureka-server-0.0.1-SNAPSHOT.jar
    networks:
      - servicodevendas-network
    depends_on:
      - rabbitmq
    restart: on-failure

  api-gateway:
    image: openjdk:21-jdk-slim
    container_name: servicodevendas-gateway
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    ports:
      - "8080:8080"
    command: java -jar target/api-gateway-0.0.1-SNAPSHOT.jar
    networks:
      - servicodevendas-network
    depends_on:
      - eureka-server
    restart: on-failure

  sales-service:
    image: openjdk:21-jdk-slim
    container_name: servicodevendas-sales
    working_dir: /app
    volumes:
      - ./sales-service:/app
    ports:
      - "8081:8081"
    command: java -jar target/sales-service-0.0.1-SNAPSHOT.jar
    networks:
      - servicodevendas-network
    env_file:
      - .env
    depends_on:
      - eureka-server
      - rabbitmq
    restart: on-failure

  tax-service:
    image: openjdk:21-jdk-slim
    container_name: servicodevendas-tax
    working_dir: /app
    volumes:
      - ./tax-service:/app
    ports:
      - "8082:8082"
    command: java -jar target/tax-service-0.0.1-SNAPSHOT.jar
    networks:
      - servicodevendas-network
    depends_on:
      - eureka-server
    restart: on-failure

  sales-registry-service:
    image: openjdk:21-jdk-slim
    container_name: servicodevendas-registry
    working_dir: /app
    volumes:
      - ./sales-registry-service:/app
    ports:
      - "8083:8083"
    command: java -jar target/sales-registry-service-0.0.1-SNAPSHOT.jar
    networks:
      - servicodevendas-network
    env_file:
      - .env
    depends_on:
      - eureka-server
      - rabbitmq
    restart: on-failure

volumes:
  rabbitmq_data:

networks:
  servicodevendas-network:
    driver: bridge 